# Generated by Django 4.2.2 on 2023-10-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
